name: CI/CD on Self-Hosted Runner

on:
  push:
    branches: [ "main" ]  
  pull_request:

jobs:
  build-and-deploy:
    runs-on: self-hosted   # Twój runner na AWS
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm ci
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No dependencies file found, skipping"
          fi

      - name: Run tests
        run: |
          if [ -f package.json ]; then
            npm test || true
          elif [ -d tests ]; then
            pytest || true
          else
            echo "No tests found, skipping"
          fi

      - name: Build project
        run: |
          if [ -f package.json ]; then
            npm run build
          else
            echo "No build step defined"
          fi

      - name: Deploy (example)
        run: |
          mkdir -p ~/deploy
          cp -r . ~/deploy/
          echo "✅ App deployed to ~/deploy"
